<?php
return ['project-id-version'=>'One Page Quick Checkout for WooCommerce','report-msgid-bugs-to'=>'','pot-creation-date'=>'2026-03-17 04:47+0000','po-revision-date'=>'2026-03-17 08:48+0000','last-translator'=>'','language-team'=>'বাংলা','language'=>'bn_BD','plural-forms'=>'nplurals=2; plural=n != 1;','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-loco-version'=>'2.8.3; wp-6.9; php-8.2.29','x-domain'=>'one-page-quick-checkout-for-woocommerce','messages'=>['
After Add to Cart Button
'=>'কার্টে যোগ করুন বাটনের পরে','
Auto
'=>'স্বয়ংক্রিয়','
Button
'=>'বাটন','
Custom Style
'=>'কাস্টম স্টাইল','
Direct Checkout
'=>'সরাসরি চেকআউট','
No Icon
'=>'কোনো আইকন নেই','
No Redirect
'=>'কোনো পুনঃনির্দেশ নেই','
Same as Desktop
'=>'ডেস্কটপের মতোই','
Two Columns (Product & Checkout)
'=>'দুই কলাম (পণ্য ও চেকআউট)',' Advanced'=>'উন্নত',' Button Behavior'=>'বাটন আচরণ','"View Full Details" Button Text'=>'সম্পূর্ণ বিবরণ দেখুন','%s (optional)'=>'%s (ঐচ্ছিক)','(Use plugin default)'=>'(প্লাগইন ডিফল্ট ব্যবহার করুন)','A modern, stylish side-drawer cart that users can access from any page for improved convenience.

'=>'একটি আধুনিক, স্টাইলিশ সাইড-ড্রয়ার কার্ট যা উন্নত সুবিধার জন্য ব্যবহারকারীরা যেকোনো পৃষ্ঠা থেকে অ্যাক্সেস করতে পারে।','Above Checkout Form'=>'চেকআউট ফর্মের উপরে','Accent color for secondary elements'=>'মাধ্যমিক উপাদানগুলির জন্য অ্যাকসেন্ট রঙ','Add a custom CSS ID'=>'একটি কাস্টম CSS আইডি যোগ করুন','Add custom CSS classes separated by spaces'=>'কাস্টম CSS ক্লাসগুলি স্পেস দ্বারা পৃথক করে যোগ করুন','Add custom CSS for advanced button styling. Use the class .opqcfw-btn to target the button.'=>'উন্নত বোতাম স্টাইলিংয়ের জন্য কাস্টম CSS যোগ করুন। বোতামটিকে লক্ষ্য করতে .opqcfw-btn ক্লাসটি ব্যবহার করুন।','Add custom CSS for advanced button styling. Use the class .opqvfw-btn to target the button and .opqvfw-modal to target the modal.'=>'উন্নত বোতাম স্টাইলিংয়ের জন্য কাস্টম CSS যোগ করুন। বোতামটিকে লক্ষ্য করতে .opqvfw-btn ক্লাস এবং মডালটিকে লক্ষ্য করতে .opqvfw-modal ক্লাস ব্যবহার করুন।','Add custom CSS for advanced button styling. Use the class .product_type_simple.add_to_cart_button to target the button.'=>'উন্নত বোতাম স্টাইলিংয়ের জন্য কাস্টম CSS যোগ করুন। বোতামটিকে লক্ষ্য করতে .product_type_simple.add_to_cart_button ক্লাসটি ব্যবহার করুন।','Add Image Before Product'=>'পণ্যের আগে ছবি যোগ করুন','Add New Badge'=>'নতুন ব্যাজ যোগ করুন','Add products to cart without page reload using AJAX.

'=>'AJAX ব্যবহার করে পেজ রিলোড ছাড়াই কার্টে পণ্য যোগ করুন।','Add subtle shadow effects to elements'=>'উপাদানগুলিতে সূক্ষ্ম ছায়া প্রভাব যুক্ত করুন','Add To Cart'=>'কার্টে যোগ করুন','Add to cart'=>'কার্টে যোগ করুন','Add To Cart Behavior'=>'কার্টে যোগ করার আচরণ','Add to Cart Button'=>'কার্টে যোগ করুন বোতাম','Add to Cart on Page Load'=>'পেজ লোডে কার্টে যোগ করুন','Add your custom CSS styles here'=>'এখানে আপনার কাস্টম সিএসএস স্টাইল যোগ করুন','Additional information'=>'অতিরিক্ত তথ্য','Address 1

'=>'ঠিকানা ১','Address 2

'=>'ঠিকানা ২','Adjust the rounded corners of elements'=>'উপাদানগুলির গোলাকার কোণগুলি সামঞ্জস্য করুন','Advanced'=>'উন্নত','Advanced Options'=>'উন্নত বিকল্পসমূহ','Advanced Settings'=>'উন্নত সেটিংস','Advanced: Custom HTML'=>'উন্নত: কাস্টম HTML','After Add to Cart Button'=>'কার্টে যোগ করার বোতামের পরে','After Add to Cart Button
'=>'কার্টে যোগ করুন বোতামের পরে','After Product'=>'পণ্যের পরে','After Product Excerpt'=>'পণ্য সারাংশের পরে','After Product Image
'=>'পণ্যের ছবির পরে','After Product Price'=>'পণ্যের দামের পরে','After Product Rating'=>'পণ্য রেটিং এর পরে','After Product Title'=>'পণ্যের শিরোনামের পরে','AJAX Add to Cart'=>'এজ্যাক্স কার্টে যোগ করুন','All Pages'=>'সমস্ত পৃষ্ঠা','Alternative Style'=>'বিকল্প শৈলী','Always Hide'=>'সর্বদা লুকান','Always Show'=>'সর্বদা দেখান','Analytics Integration'=>'অ্যানালিটিক্স ইন্টিগ্রেশন','Archive Pages'=>'আর্কাইভ পেজসমূহ','Arrow'=>'তীর','Arrow Icon'=>'তীর আইকন','At Least One Product in Cart'=>'কার্টে কমপক্ষে একটি পণ্য','Attribute Terms'=>'অ্যাট্রিবিউট পদাবলী','Auto'=>'স্বয়ংক্রিয়','Auto add to cart'=>'স্বয়ংক্রিয়ভাবে কার্টে যোগ করুন','Auto-pick Variation (default / first in-stock)'=>'স্বয়ংক্রিয়ভাবে ভ্যারিয়েশন বাছাই করুন (ডিফল্ট / প্রথম স্টক আছে)','Automatically add the first product to cart when the page loads.'=>'পৃষ্ঠা লোড হলে স্বয়ংক্রিয়ভাবে প্রথম পণ্যটি কার্টে যুক্ত করুন।','Automatically add the product to cart when the page loads.'=>'পৃষ্ঠা লোড হওয়ার সাথে সাথে স্বয়ংক্রিয়ভাবে পণ্যটি কার্টে যুক্ত করুন।','Award'=>'পুরস্কার','Background Color'=>'পটভূমির রঙ','Badge Position'=>'ব্যাজ অবস্থান','Badge Style'=>'ব্যাজ স্টাইল','Basic Shortcode:
'=>'বেসিক শর্টকোড:','Basket'=>'ঝুড়ি','Basket Icon'=>'ঝুড়ি আইকন','Before Add to Cart Button'=>'কার্টে যোগ করার আগে','Before Product Title'=>'পণ্যের শিরোনামের আগে','Behavior'=>'আচরণ','Below Checkout Form'=>'চেকআউট ফর্মের নিচে','Billing details'=>'বিলিংয়ের বিবরণ','Border Color'=>'বর্ডার রঙ','Border Radius'=>'বর্ডার ব্যাসার্ধ','Bottom'=>'নিচে','Bottom of Add to Cart Button'=>'অ্যাড টু কার্ট বাটনের নিচে','Button'=>'বাটন','Button Color
'=>'বাটনের রঙ','Button Display '=>'বাটন প্রদর্শন','Button Font Size'=>'বাটন ফন্টের আকার','Button Icon'=>'বাটন আইকন','Button Padding'=>'বাটন প্যাডিং','Button Position'=>'বাটন অবস্থান','Button Position on Archive Page'=>'আর্কাইভ পৃষ্ঠায় বোতামের অবস্থান','Button Position on Single Page'=>'একক পৃষ্ঠায় বোতামের অবস্থান','Button Style'=>'বাটন স্টাইল','Button Style Settings'=>'বাটন স্টাইল সেটিংস','Button Text'=>'বোতামের লেখা','Button Typography'=>'বাটন টাইপোগ্রাফি','Button UI'=>'বাটন ইউআই','Button Width'=>'বোতামের প্রস্থ','Buy Now'=>'এখনই কিনুন','Buy Now Button'=>'এখনই কিনুন','Buy Now Button
'=>'এখনই কিনুন বাটন','Buy Now Button Anywhere
'=>'যেকোনো স্থান থেকে এখনই কিনুন বোতাম','By Attribute'=>'অ্যাট্রিবিউট অনুসারে','By Category & Tag'=>'বিভাগ ও ট্যাগ অনুসারে','By Product IDs'=>'পণ্য আইডি অনুসারে','Calculator'=>'ক্যালকুলেটর','Cart'=>'কার্ট','Cart Checkout Behavior'=>'কার্ট চেকআউট আচরণ','Cart Icon'=>'কার্ট আইকন','Cart Text Changes'=>'কার্ট টেক্সট পরিবর্তন','Category'=>'বিভাগ','Change the text shown on the "View Full Details" button inside the Quick View popup.'=>'কুইক ভিউ পপআপের মধ্যে "ভিউ ফুল ডিটেইলস" বোতামে প্রদর্শিত লেখা পরিবর্তন করুন।','Checkmark'=>'টিক চিহ্ন','Checkout'=>'চেকআউট','Checkout (Preview)'=>'চেকআউট (প্রিভিউ)','Checkout Button'=>'চেকআউট বাটন','Checkout Form'=>'চেকআউট ফর্ম','Checkout Form Manage'=>'চেকআউট ফর্ম পরিচালনা','Checkout Icon'=>'চেকআউট আইকন','Checkout in Variable Product
'=>'পরিবর্তনশীল পণ্যের জন্য চেকআউট','Checkout Layout'=>'চেকআউট লেআউট','Checkout Method'=>'চেকআউট পদ্ধতি','Checkout renderer not available.'=>'চেকআউট রেন্ডারার উপলব্ধ নয়।','Checkout Settings'=>'চেকআউট সেটিংস','Choose button size optimization for mobile devices.

'=>'মোবাইল ডিভাইসের জন্য বোতামের আকার অপ্টিমাইজেশান নির্বাচন করুন।','Choose how products will be displayed on the checkout page'=>'চেকআউট পৃষ্ঠায় পণ্যগুলি কীভাবে প্রদর্শিত হবে তা নির্বাচন করুন','Choose how the quick checkout process should behave when a customer clicks the button.'=>'গ্রাহক বোতামে ক্লিক করলে কুইক চেকআউট প্রক্রিয়াটি কীভাবে কাজ করবে তা বেছে নিন।','Choose how the quick view trigger should appear to customers.'=>'গ্রাহকদের কাছে কুইক ভিউ ট্রিগারটি কীভাবে প্রদর্শিত হবে তা বেছে নিন।','Choose how to display notifications when products are added to cart.

'=>'কার্টে পণ্য যোগ করার সময় বিজ্ঞপ্তিগুলি কীভাবে প্রদর্শন করা হবে তা বেছে নিন।','Choose the animation effect when opening the quick view modal.'=>'কুইক ভিউ মডাল খোলার সময় অ্যানিমেশন প্রভাবটি বেছে নিন।','Choose the appearance of checkout buttons'=>'চেকআউট বোতামের চেহারা নির্বাচন করুন','Choose the behavior of the cart checkout process.'=>'কার্ট চেকআউট প্রক্রিয়ার আচরণ নির্বাচন করুন।','Choose the size of the quick view modal popup'=>'কুইক ভিউ মডাল পপআপের আকার নির্বাচন করুন','Choose variation selection Layout.'=>'পরিবর্তন নির্বাচন বিন্যাস নির্বাচন করুন।','Choose where to display the direct checkout button on product pages.'=>'পণ্য পৃষ্ঠাগুলিতে সরাসরি চেকআউট বোতামটি কোথায় প্রদর্শন করবেন তা চয়ন করুন।','Choose where to display the direct checkout button on single pages.'=>'একক পৃষ্ঠায় সরাসরি চেকআউট বোতামটি কোথায় প্রদর্শন করবেন তা নির্বাচন করুন।','Choose where to display the quick view button on product listings.'=>'পণ্য তালিকায় কুইক ভিউ বাটন কোথায় প্রদর্শন করা হবে তা নির্বাচন করুন।','Choose whether to redirect customers after adding products to cart.

'=>'কার্টে পণ্য যোগ করার পরে গ্রাহকদের পুনঃনির্দেশিত করা হবে কিনা তা নির্বাচন করুন।','City'=>'শহর','Clear Cart Before Adding'=>'যোগ করার আগে কার্ট খালি করুন','Clear cart before adding'=>'যোগ করার আগে কার্ট খালি করুন','Clear existing cart items when a multi-product one-page checkout page loads.'=>'মাল্টি-প্রোডাক্ট এক-পৃষ্ঠার চেকআউট পৃষ্ঠা লোড হলে বিদ্যমান কার্ট আইটেমগুলি সাফ করুন।','Clear existing cart items when the one-page checkout product page loads.'=>'এক-পৃষ্ঠার চেকআউট পণ্য পৃষ্ঠা লোড হলে বিদ্যমান কার্ট আইটেমগুলি সাফ করুন।','Clock'=>'ঘড়ি','Close on Add to Cart'=>'কার্টে যোগ করুন বন্ধ করুন','Color'=>'রঙ','Colors & Buttons'=>'রঙ ও বোতাম','Combine'=>'একত্র করুন','Company'=>'কোম্পানি','Compatibility Settings'=>'সামঞ্জস্যতা সেটিংস','Complete your purchase using the form below.'=>'নিচের ফর্মটি ব্যবহার করে আপনার কেনাকাটা সম্পন্ন করুন।','Configure settings for the multi-product one-page checkout shortcode. Use:
[plugincy_one_page_checkout product_ids="152,153,151,142" template="product-tabs"]'=>'মাল্টি-প্রোডাক্ট এক-পৃষ্ঠার চেকআউট শর্টকোডের জন্য সেটিংস কনফিগার করুন। ব্যবহার করুন:
[plugincy_one_page_checkout product_ids="152,153,151,142" template="product-tabs"]','Configure the appearance and behavior of your floating cart. Enable the floating cart to provide users with quick access to their cart from any page on your site.

'=>'আপনার ফ্লোটিং কার্টের চেহারা এবং আচরণ কনফিগার করুন। আপনার সাইটের যেকোনো পৃষ্ঠা থেকে ব্যবহারকারীদের তাদের কার্টে দ্রুত অ্যাক্সেস দেওয়ার জন্য ফ্লোটিং কার্ট সক্ষম করুন।','Configure the position of the floating cart.'=>'ফ্লোটিং কার্টের অবস্থান কনফিগার করুন।','Configure the style of the floating cart button.'=>'ফ্লোটিং কার্ট বোতামের স্টাইল কনফিগার করুন।','Configure your checkout in minutes with our intuitive options.

'=>'আমাদের স্বজ্ঞাত বিকল্পগুলির সাথে কয়েক মিনিটের মধ্যে আপনার চেকআউট কনফিগার করুন।','Contact Support'=>'সহায়তার জন্য যোগাযোগ করুন','Contribute to Plugincy'=>'Plugincy-তে অবদান রাখুন','Control how Add to Cart buttons appear on product archive pages.'=>'পণ্য আর্কাইভ পেজগুলিতে \'কার্টে যোগ করুন\' বোতামগুলি কীভাবে প্রদর্শিত হবে তা নিয়ন্ত্রণ করুন।','Control how Add to Cart buttons behave on product archive pages.

'=>'পণ্য আর্কাইভ পৃষ্ঠাগুলিতে অ্যাড টু কার্ট বোতামগুলি কীভাবে কাজ করবে তা নিয়ন্ত্রণ করুন।','Control the spacing between elements'=>'উপাদানগুলির মধ্যেকার ব্যবধান নিয়ন্ত্রণ করুন','Control where quick view scripts are loaded to improve compatibility and performance.'=>'দ্রুত দেখার স্ক্রিপ্টগুলি কোথায় লোড হবে তা নিয়ন্ত্রণ করুন যাতে সামঞ্জস্যতা এবং কর্মক্ষমতা উন্নত হয়।','Country'=>'দেশ','Country / Region'=>'দেশ / অঞ্চল','Credit Card'=>'ক্রেডিট কার্ড','CSS Classes'=>'সিএসএস ক্লাস','CSS ID'=>'CSS আইডি','Current License Key'=>'বর্তমান লাইসেন্স কী','Custom CSS'=>'কাস্টম CSS','Custom HTML for trust badges. You can use dashicons or include your own images.'=>'ট্রাস্ট ব্যাজের জন্য কাস্টম HTML। আপনি ড্যাশকন ব্যবহার করতে পারেন অথবা আপনার নিজস্ব ছবি অন্তর্ভুক্ত করতে পারেন।','Custom Style'=>'কাস্টম স্টাইল','Custom Width'=>'কাস্টম প্রস্থ','Customer'=>'গ্রাহক','Customizable Add to Cart'=>'কাস্টমাইজযোগ্য কার্টে যোগ করুন','Customize how notifications are displayed when products are added to cart.

'=>'পণ্য কার্টে যোগ করার সময় বিজ্ঞপ্তিগুলি কীভাবে প্রদর্শিত হবে তা কাস্টমাইজ করুন।','Customize the checkout form fields and headings to enhance user experience.'=>'ব্যবহারকারীর অভিজ্ঞতা উন্নত করতে চেকআউট ফর্মের ফিল্ড এবং শিরোনাম কাস্টমাইজ করুন।','Customize the headings of the checkout form fields to enhance user experience.'=>'চেকআউট ফর্ম ফিল্ডগুলির শিরোনামগুলি ব্যবহারকারীর অভিজ্ঞতা উন্নত করতে কাস্টমাইজ করুন।','Customize the success message shown after adding to cart. Use {product} as a placeholder for the product name.

'=>'কার্টে যোগ করার পরে প্রদর্শিত সাফল্যের বার্তাটি কাস্টমাইজ করুন। পণ্যের নামের জন্য {product} কে প্লেসহোল্ডার হিসাবে ব্যবহার করুন।','Customize the text displayed on the Add to Cart button for grouped products.'=>'গ্রুপড পণ্যের জন্য \'কার্টে যোগ করুন\' বোতামে প্রদর্শিত লেখাটি কাস্টমাইজ করুন।','Customize the text displayed on the Add to Cart button for simple products.'=>'সাধারণ পণ্যের জন্য \'কার্টে যোগ করুন\' বোতামে প্রদর্শিত লেখাটি কাস্টমাইজ করুন।','Customize the text displayed on the Add to Cart button for simple products.

'=>'সাধারণ পণ্যের জন্য \'কার্টে যোগ করুন\' বোতামে প্রদর্শিত লেখাটি কাস্টমাইজ করুন।','Customize the text displayed on the Add to Cart button for variable products.'=>'পরিবর্তনশীল পণ্যের জন্য \'কার্টে যোগ করুন\' বোতামে প্রদর্শিত পাঠ্য কাস্টমাইজ করুন।','Customize the text displayed on the Add to Cart button for variable products.

'=>'পরিবর্তনশীল পণ্যের জন্য \'কার্টে যোগ করুন\' বোতামে প্রদর্শিত লেখাটি কাস্টমাইজ করুন।','Customize the text displayed on the direct checkout button.'=>'সরাসরি চেকআউট বোতামে প্রদর্শিত পাঠ্যটি কাস্টমাইজ করুন।','Customize the text displayed on the quick view button.'=>'কুইক ভিউ বোতামে প্রদর্শিত লেখাটি কাস্টমাইজ করুন।','Customize the text displayed on the Read More button.'=>'আরও পড়ুন বোতামে প্রদর্শিত পাঠ্য কাস্টমাইজ করুন।','Customize the text displayed on the Read More button.

'=>'আরও পড়ুন বোতামে প্রদর্শিত পাঠ্য কাস্টমাইজ করুন।','Dashboard'=>'ড্যাশবোর্ড','Deactivate License'=>'লাইসেন্স নিষ্ক্রিয় করুন','Default (WooCommerce Setting)

'=>'ডিফল্ট (WooCommerce সেটিংস)','Default Quantity'=>'ডিফল্ট পরিমাণ','Default WooCommerce Style'=>'ডিফল্ট WooCommerce স্টাইল','Detect Product from Context'=>'প্রসঙ্গ থেকে পণ্য সনাক্ত করুন','Disable Cart Page'=>'কার্ট পৃষ্ঠা অক্ষম করুন','Disable continue shopping button'=>'কেনাকাটা চালিয়ে যান বোতামটি নিষ্ক্রিয় করুন','Discount '=>'ছাড়','Display a \'Checkout\' link in the notification message.

'=>'নোটিফিকেশন বার্তায় একটি \'চেকআউট\' লিঙ্ক প্রদর্শন করুন।','Display a \'View Cart\' link in the notification message.

'=>'নোটিফিকেশন বার্তায় একটি \'কার্ট দেখুন\' লিঙ্ক প্রদর্শন করুন।','Display quantity selector on shop/archive pages before adding to cart.

'=>'শপ/আর্কাইভ পেজে কার্টে যোগ করার আগে পরিমাণ নির্বাচক প্রদর্শন করুন।','Display Settings'=>'প্রদর্শন সেটিংস','Display Template'=>'ডিসপ্লে টেমপ্লেট','Display trust signals and security badges on the checkout page.'=>'চেকআউট পৃষ্ঠায় ট্রাস্ট সিগন্যাল এবং নিরাপত্তা ব্যাজ প্রদর্শন করুন।','District'=>'জেলা','DIV'=>'ডিআইভি','Drawer'=>'ড্রয়ার','Drawer Position'=>'ড্রয়ারের অবস্থান','Easily modify the Add to Cart button text, style, and functionality for a more engaging shopping experience.

'=>'আরও আকর্ষক কেনাকাটার অভিজ্ঞতার জন্য সহজেই \'কার্টে যোগ করুন\' বোতামের লেখা, স্টাইল এবং কার্যকারিতা পরিবর্তন করুন।','Element Spacing'=>'উপাদান ব্যবধান','Email'=>'ইমেল','Email address'=>'ইমেল ঠিকানা','Empty Cart on Page Load'=>'পেজ লোডে কার্ট খালি করুন','Enable "Add Image Before Product" to display product images before their titles in the checkout form.'=>'চেকআউট ফর্মে পণ্যের শিরোনামের আগে পণ্যের ছবি প্রদর্শন করতে "Add Image Before Product" সক্ষম করুন।','Enable "At Least One Product in Cart" to add at least one product in the cart.'=>'কার্টে কমপক্ষে একটি পণ্য যোগ করতে "কার্টে কমপক্ষে একটি পণ্য" সক্ষম করুন।','Enable "At Least One Product in Cart" to add at least one product in the cart.

'=>'কার্টে কমপক্ষে একটি পণ্য যোগ করতে "কার্টে কমপক্ষে একটি পণ্য" সক্ষম করুন।','Enable "Disable Cart Page" to remove the cart page from your WooCommerce store. This will redirect customers directly to the checkout page.'=>'আপনার WooCommerce স্টোর থেকে কার্ট পেজটি সরাতে "Disable Cart Page" চালু করুন। এটি গ্রাহকদের সরাসরি চেকআউট পেজে পুনঃনির্দেশিত করবে।','Enable "Disable Cart Page" to remove the cart page from your WooCommerce store. This will redirect customers directly to the checkout page.

'=>'আপনার WooCommerce স্টোর থেকে কার্ট পেজটি সরাতে "Disable Cart Page" সক্ষম করুন। এটি গ্রাহকদের সরাসরি চেকআউট পেজে পুনঃনির্দেশিত করবে।','Enable "Link Product Name in Checkout Page" to make the product names clickable, redirecting customers to the product page.'=>'চেকআউট পৃষ্ঠায় "পণ্যের নাম লিঙ্ক করুন" সক্ষম করুন যাতে পণ্যের নামগুলিতে ক্লিক করা যায় এবং গ্রাহকদের পণ্যের পৃষ্ঠায় পুনঃনির্দেশিত করা যায়।','Enable "Link Product Name in Checkout Page" to make the product names clickable, redirecting customers to the product page.

'=>'চেকআউট পৃষ্ঠায় "পণ্যের নাম লিঙ্ক করুন" সক্ষম করুন যাতে পণ্যের নামগুলিতে ক্লিক করা যায় এবং গ্রাহকদের পণ্যের পৃষ্ঠায় পুনঃনির্দেশিত করা যায়।','Enable "Product Quantity Controller" to manage product quantities in the checkout form.'=>'চেকআউট ফর্মে পণ্যের পরিমাণ পরিচালনা করতে "প্রোডাক্ট কোয়ান্টিটি কন্ট্রোলার" সক্ষম করুন।','Enable \'Add Image Before Product\' to display product images before their titles in the checkout form.'=>'চেকআউট ফর্মে পণ্যের শিরোনামের আগে পণ্যের ছবি প্রদর্শন করতে \'Add Image Before Product\' সক্ষম করুন।','Enable \'Product Quantity Controller\' to manage product quantities in the checkout form.'=>'চেকআউট ফর্মে পণ্যের পরিমাণ পরিচালনা করতে \'প্রোডাক্ট কোয়ান্টিটি কন্ট্রোলার\' সক্ষম করুন।','Enable AJAX Add to Cart'=>'এজ্যাক্স অ্যাড টু কার্ট সক্ষম করুন','Enable Box Shadow'=>'বক্স শ্যাডো সক্ষম করুন','Enable Custom Quick View in the general settings tab to access these options.
'=>'সাধারণ সেটিংস ট্যাবে এই বিকল্পগুলি অ্যাক্সেস করতে কাস্টম কুইক ভিউ সক্ষম করুন।','Enable Direct Checkout'=>'সরাসরি চেকআউট সক্ষম করুন','Enable direct checkout to allow customers to bypass the cart and proceed directly to checkout, streamlining the purchasing process.

'=>'কার্ট এড়িয়ে গ্রাহকদের সরাসরি চেকআউটে যাওয়ার অনুমতি দিতে সরাসরি চেকআউট সক্ষম করুন, যা ক্রয় প্রক্রিয়াটিকে সুগম করে।','Enable for All Products'=>'সমস্ত পণ্যের জন্য সক্ষম করুন','Enable for Guest Checkout'=>'অতিথির জন্য চেকআউট সক্ষম করুন','Enable One Page Checkout'=>'এক পৃষ্ঠার চেকআউট সক্ষম করুন','Enable one page checkout for this product'=>'এই পণ্যের জন্য এক পৃষ্ঠার চেকআউট সক্ষম করুন','Enable one-page checkout for all products without individual selection.'=>'সমস্ত পণ্যের জন্য একক-পৃষ্ঠার চেকআউট সক্ষম করুন, পৃথক নির্বাচন ছাড়াই।','Enable one-page checkout for single product page.'=>'একক পণ্য পৃষ্ঠার জন্য এক-পৃষ্ঠার চেকআউট সক্ষম করুন।','Enable or disable custom Add to Cart styling and functionality.'=>'কাস্টম অ্যাড টু কার্ট স্টাইলিং এবং কার্যকারিতা সক্ষম বা নিষ্ক্রিয় করুন।','Enable or disable custom Add to Cart styling and functionality.

'=>'কাস্টম অ্যাড টু কার্ট স্টাইলিং এবং কার্যকারিতা সক্ষম বা নিষ্ক্রিয় করুন।','Enable or disable the direct checkout functionality across your WooCommerce store.'=>'আপনার WooCommerce স্টোর জুড়ে সরাসরি চেকআউট কার্যকারিতা সক্ষম বা নিষ্ক্রিয় করুন।','Enable or disable the quick view functionality across your WooCommerce store.'=>'আপনার WooCommerce স্টোর জুড়ে কুইক ভিউ কার্যকারিতা সক্ষম বা নিষ্ক্রিয় করুন।','Enable or disable the sticky cart functionality.'=>'স্টিকি কার্ট কার্যকারিতা সক্ষম বা নিষ্ক্রিয় করুন।','Enable Quick View'=>'কুইক ভিউ চালু করুন','Enable Sticky Cart'=>'স্টিকি কার্ট সক্ষম করুন','Enable this if you experience display issues with your theme.'=>'আপনার থিমের সাথে ডিসপ্লে সমস্যা হলে এটি সক্ষম করুন।','Enable Trust Badges'=>'ট্রাস্ট ব্যাজ সক্ষম করুন','Enhance WooCommerce with popup checkout, cart drawer, and flexible checkout templates to boost conversions.'=>'পপআপ চেকআউট, কার্ট ড্রয়ার এবং নমনীয় চেকআউট টেমপ্লেট দিয়ে WooCommerce উন্নত করুন যাতে রূপান্তর বৃদ্ধি পায়।','Enhance your WooCommerce checkout experience with these powerful features.'=>'এই শক্তিশালী বৈশিষ্ট্যগুলির সাথে আপনার WooCommerce চেকআউট অভিজ্ঞতা উন্নত করুন।','Enter attribute name (e.g., color, size, brand)'=>'অ্যাট্রিবিউটের নাম লিখুন (যেমন: রঙ, আকার, ব্র্যান্ড)','Enter attribute terms separated by commas (e.g., red,blue,green)'=>'অ্যাট্রিবিউট পদগুলি কমা দ্বারা পৃথক করে লিখুন (যেমন, লাল, নীল, সবুজ)','Enter category slugs separated by commas (e.g., electronics,clothing)'=>'কমা দ্বারা পৃথক করা ক্যাটাগরি স্ল্যাগ লিখুন (যেমন, electronics,clothing)','Enter specific product IDs separated by commas (e.g., 152,153,151,142)'=>'কমা দ্বারা পৃথক করা নির্দিষ্ট পণ্যের আইডি লিখুন (যেমন, ১৫২,১৫৩,১৫১,১৪২)','Enter tag slugs separated by commas (e.g., featured,sale)'=>'কমা দ্বারা পৃথক করা ট্যাগ স্ল্যাগগুলি লিখুন (যেমন, বৈশিষ্ট্যযুক্ত,বিক্রয়)','Enter your license key to download and activate the Pro version.'=>'প্রো সংস্করণ ডাউনলোড এবং সক্রিয় করতে আপনার লাইসেন্স কী লিখুন।','Error adding product to cart'=>'কার্টে পণ্য যোগ করতে ত্রুটি','Error loading product information. Please try again.'=>'পণ্য লোড করতে ত্রুটি। অনুগ্রহ করে আবার চেষ্টা করুন।','Error, duplicate 1: 
After Add to Cart Button
'=>'ত্রুটি, সদৃশ ১:
কার্টে যোগ করুন বোতামের পরে','Error, duplicate 2: Error, duplicate 1: 
After Add to Cart Button
'=>'ত্রুটি, সদৃশ ২: ত্রুটি, সদৃশ ১:
কার্টে যোগ করুন বাটনের পরে','Event Action'=>'ইভেন্ট অ্যাকশন','Event Category'=>'ইভেন্ট বিভাগ','External/Affiliate Products'=>'বাহ্যিক/অ্যাফিলিয়েট পণ্য','Extra CSS Classes'=>'অতিরিক্ত CSS ক্লাস','Fade'=>'ফেড','Fast Setup
'=>'দ্রুত সেটআপ','Featured Products'=>'বৈশিষ্ট্যযুক্ত পণ্য','Features'=>'বৈশিষ্ট্যসমূহ','Filled'=>'পূরণ করা হয়েছে','First Name'=>'প্রথম নাম','First name'=>'প্রথম নাম','Floating Cart'=>'ফ্লোটিং কার্ট','Floating Cart
'=>'ফ্লোটিং কার্ট','Floating Cart Benefits:
'=>'ফ্লোটিং কার্টের সুবিধা:','Floating Cart Settings'=>'ফ্লোটিং কার্ট সেটিংস','Font Size'=>'ফন্টের আকার','Force Button CSS'=>'বাটন সিএসএস জোর করুন','Force Display'=>'জোর করে প্রদর্শন','Force Login Before Checkout'=>'চেকআউটের আগে লগইন বাধ্যতামূলক করুন','Form Position'=>'ফর্ম অবস্থান','Full Width'=>'পূর্ণ প্রস্থ','General Settings'=>'সাধারণ সেটিংস','General settings for the floating cart.'=>'ফ্লোটিং কার্টের জন্য সাধারণ সেটিংস।','Get Pro'=>'প্রো পান','Get Support'=>'সহায়তা পান','Grid (2 columns)'=>'গ্রিড (২ কলাম)','Grouped Product Button Text'=>'গ্রুপযুক্ত পণ্যের বোতামের লেখা','Grouped Products'=>'গ্রুপযুক্ত পণ্য','H1'=>'এইচ১','H2'=>'এইচ২','H3'=>'এইচ৩','H4'=>'H4','H5'=>'এইচ৫','H6'=>'H6','Have a coupon?'=>'আপনার কি কোনো কুপন আছে?','Heading Manage'=>'পরিচালনা করুন','Height'=>'উচ্চতা','Hide Add to Cart Button'=>'কার্ট যোগ করুন বোতামটি লুকান','Hide Additional Details
'=>'অতিরিক্ত বিবরণ লুকান','Hide Billing details
'=>'বিলিংয়ের বিবরণ লুকান','Hide license key'=>'লাইসেন্স কী লুকান','Hide Order Review Heading
'=>'অর্ডার রিভিউ হেডিং লুকান','Hide Payment Options
'=>'পেমেন্টের বিকল্পগুলি লুকান','Hide Privacy Policy Text
'=>'গোপনীয়তা নীতি পাঠ্য লুকান','Hide Product Table
'=>'পণ্য সারণী লুকান','Hide Select Option Button'=>'বিকল্প নির্বাচন লুকান বোতাম','Hide Shipping Address
'=>'শিপিং ঠিকানা লুকান','Hide the regular Add to Cart button on one-page checkout product pages.'=>'এক-পৃষ্ঠার চেকআউট পণ্য পৃষ্ঠাগুলিতে নিয়মিত \'কার্টে যোগ করুন\' বোতামটি লুকান।','Hide Top Coupon
'=>'শীর্ষ কুপন লুকান','Horizontal Row'=>'অনুভূমিক সারি','Hover Background'=>'হোভার ব্যাকগ্রাউন্ড','Hover Background Color'=>'হোভার ব্যাকগ্রাউন্ড কালার','Hover Text Color'=>'হোভার টেক্সট কালার','How long to display the notification for (in milliseconds).'=>'বিজ্ঞপ্তিটি কতক্ষণ প্রদর্শন করা হবে (মিলিসেকেন্ডে)।','https://plugincy.com'=>'https://plugincy.com','https://plugincy.com/one-page-quick-checkout-for-woocommerce/'=>'https://plugincy.com/bn/one-page-quick-checkout-for-woocommerce/','I want to use custom HTML instead'=>'আমি কাস্টম HTML ব্যবহার করতে চাই','Icon'=>'আইকন','Icon Only
'=>'আইকন মাত্র','Icon Position'=>'আইকন অবস্থান','Icon Size'=>'আইকনের আকার','Icon:'=>'আইকন:','If enabled and a Product ID is set, the cart will be emptied first.'=>'যদি সক্ষম করা হয় এবং একটি প্রোডাক্ট আইডি সেট করা থাকে, তাহলে কার্টটি প্রথমে খালি করা হবে।','If set, this product will be added to the cart. For variations, also set Variation ID.'=>'সেট করা থাকলে, এই পণ্যটি কার্টে যোগ করা হবে। ভ্যারিয়েশনের জন্য, ভ্যারিয়েশন আইডি-ও সেট করুন।','If you have a coupon code, please apply it below.'=>'আপনার যদি কোনো কুপন কোড থাকে, তাহলে অনুগ্রহ করে নিচে সেটি প্রয়োগ করুন।','Improved UX: No page reloads or redirects needed to manage cart contents
'=>'উন্নত ইউএক্স: কার্টের বিষয়বস্তু পরিচালনা করার জন্য কোনো পেজ রিলোড বা রিডাইরেক্টের প্রয়োজন নেই','Inline Style (advanced)'=>'ইনলাইন স্টাইল (উন্নত)','Keep the Add to Cart button visible at the bottom of the screen on mobile devices.

'=>'মোবাইল ডিভাইসে স্ক্রিনের নীচে \'কার্টে যোগ করুন\' বোতামটি দৃশ্যমান রাখুন।','Keyboard Navigation'=>'কীবোর্ড নেভিগেশন','Last Name'=>'শেষ নাম','Last name'=>'শেষ নাম','Layout & Spacing'=>'লেআউট ও স্পেসিং','Learn how to use our plugin features with these step-by-step video tutorials.

'=>'এই ধাপে ধাপে ভিডিও টিউটোরিয়ালগুলির মাধ্যমে আমাদের প্লাগইন বৈশিষ্ট্যগুলি কীভাবে ব্যবহার করবেন তা শিখুন।','Leave empty to detect from current product/loop.'=>'বর্তমান পণ্য/লুপ থেকে সনাক্ত করতে খালি রাখুন।','Left'=>'বাম','Left Position'=>'বাম অবস্থান','License Active but Pro Plugin Not Running!'=>'লাইসেন্স সক্রিয় কিন্তু প্রো প্লাগইন চলছে না!','License is valid but Pro plugin is not active. Click below to reinstall and activate the Pro plugin.'=>'লাইসেন্স বৈধ কিন্তু প্রো প্লাগইন সক্রিয় নয়। প্রো প্লাগইন পুনরায় ইনস্টল এবং সক্রিয় করতে নিচে ক্লিক করুন।','License Key'=>'লাইসেন্স কী','Line Height'=>'লাইন উচ্চতা','Link Product Name in Checkout Page'=>'চেকআউট পৃষ্ঠায় পণ্যের নাম লিঙ্ক করুন','Load Scripts On'=>'স্ক্রিপ্ট লোড করুন','Loading Effect  '=>'লোডিং এফেক্ট','Lock'=>'লক','Main Shop Page'=>'প্রধান দোকান পাতা','Main theme color for buttons and highlights'=>'বাটন এবং হাইলাইটের জন্য প্রধান থিম রঙ','Manage Features'=>'বৈশিষ্ট্য পরিচালনা করুন','Manage the quick view settings for your WooCommerce products.

'=>'আপনার WooCommerce পণ্যগুলির জন্য কুইক ভিউ সেটিংস পরিচালনা করুন।','Manage Your Licenses'=>'আপনার লাইসেন্স পরিচালনা করুন','Margin'=>'মার্জিন','Mobile Button Icon Only'=>'মোবাইল বাটন আইকন মাত্র','Mobile Button Size'=>'মোবাইল বোতামের আকার','Mobile Button Text'=>'মোবাইল বাটন টেক্সট','Mobile Friendly
'=>'মোবাইল বান্ধব','Mobile Friendly: Touch-optimized interface perfect for mobile shopping
'=>'মোবাইল বান্ধব: মোবাইল কেনাকাটার জন্য উপযুক্ত টাচ-অপ্টিমাইজড ইন্টারফেস','Mobile Optimization'=>'মোবাইল অপটিমাইজেশন','Mobile Settings'=>'মোবাইল সেটিংস','Modal Size'=>'মডাল আকার','Modify & complete order below'=>'নিচের অর্ডারটি পরিবর্তন ও সম্পূর্ণ করুন','Multi Product One Page Checkout'=>'মাল্টি প্রোডাক্ট ওয়ান পেজ চেকআউট','Multi-product One Page Checkout'=>'মাল্টি-প্রোডাক্ট এক পেজ চেকআউট','New Badge'=>'নতুন ব্যাজ','Next to Payment Methods'=>'পেমেন্ট পদ্ধতির পাশে','No'=>'না','No Icon'=>'কোনো আইকন নেই','None'=>'কিছুই না','Notes'=>'নোটসমূহ','Notification Duration'=>'বিজ্ঞপ্তি সময়কাল','Notification Style '=>'বিজ্ঞপ্তি শৈলী','Notifications '=>'বিজ্ঞপ্তি','On-Sale Products'=>'বিক্রয় চলছে এমন পণ্য','One Page Checkout'=>'এক পৃষ্ঠার চেকআউট','One Page Checkout
'=>'এক পৃষ্ঠার চেকআউট','One Page Checkout in Single Product'=>'একক পণ্যের জন্য এক পৃষ্ঠার চেকআউট','One Page Quick Checkout for WooCommerce'=>'WooCommerce এর জন্য এক পৃষ্ঠার দ্রুত চেকআউট','One-Page Checkout'=>'এক-পৃষ্ঠার চেকআউট','Order notes'=>'অর্ডার নোট','Other Pages'=>'অন্যান্য পৃষ্ঠাগুলি','Others'=>'অন্যান্য ','Out of stock'=>'স্টক শেষ','Outlined'=>'রূপরেখা দেওয়া','Overlay on Product Image'=>'পণ্যের ছবির উপর ওভারলে','Overlay on Product Image Hover'=>'পণ্য ছবির উপর হোভার করলে প্রদর্শিত হবে','P'=>'পি','Padding'=>'প্যাডিং','Payment Gateways
'=>'পেমেন্ট গেটওয়ে','Phone'=>'ফোন','Phone '=>'ফোন','Place order'=>'অর্ডার দিন','Place Order Button'=>'অর্ডার করুন','Placeholder'=>'স্থানধারক','Please provide product IDs, category, tags, or attribute terms.'=>'অনুগ্রহ করে পণ্যের আইডি, বিভাগ, ট্যাগ বা অ্যাট্রিবিউট পদগুলি সরবরাহ করুন।','Plugin License'=>'প্লাগইন লাইসেন্স','Plugincy'=>'প্লাগইন','plugincy'=>'প্লাগইনসি','Plugincy Custom CSS'=>'প্লাগইন কাস্টম সিএসএস','Plus Icon'=>'যোগ করুন আইকন','Popup Checkout (Pro Features)
'=>'পপআপ চেকআউট (প্রো বৈশিষ্ট্য)','Popup Manage'=>'পপআপ পরিচালনা করুন','Position Settings'=>'অবস্থান সেটিংস','Postcode / ZIP'=>'পোস্টকোড / জিপ','Pricing Table'=>'মূল্য নির্ধারণের সারণী','Primary Color'=>'প্রাথমিক রঙ','Privacy'=>'গোপনীয়তা','Pro Features only'=>'প্রো বৈশিষ্ট্যগুলি শুধুমাত্র','Pro Version Activated!'=>'প্রো সংস্করণ সক্রিয় করা হয়েছে!','Product'=>'পণ্য','Product '=>'পণ্য','Product Accordion'=>'পণ্য অ্যাকর্ডিয়ন','Product Attribute'=>'পণ্য বৈশিষ্ট্য','Product Attribute Archives'=>'পণ্য বৈশিষ্ট্যের আর্কাইভ','Product Brand Archives'=>'পণ্য ব্র্যান্ড আর্কাইভ','Product Categories'=>'পণ্যের বিভাগসমূহ','Product Category Archives'=>'পণ্য বিভাগ আর্কাইভ','Product Gallery'=>'পণ্য গ্যালারি','Product ID'=>'পণ্য আইডি','Product IDs'=>'পণ্য আইডি','Product Image'=>'পণ্যের ছবি','Product List'=>'পণ্য তালিকা','Product Meta'=>'পণ্য মেটা','Product Pages'=>'পণ্যের পৃষ্ঠা','Product Price'=>'পণ্যের মূল্য','Product Quantity Controller'=>'পণ্যের পরিমাণ নিয়ন্ত্রক','Product Query'=>'পণ্য অনুসন্ধান','Product Rating'=>'পণ্যের রেটিং','Product Single'=>'পণ্য একক','Product Slider'=>'পণ্য স্লাইডার','Product Table'=>'পণ্য সারণী','Product Tabs'=>'পণ্য ট্যাব','Product Tag Archives'=>'পণ্য ট্যাগ আর্কাইভ','Product Tags'=>'পণ্যের ট্যাগ','Product Title'=>'পণ্যের শিরোনাম','Product Title Tag'=>'পণ্যের শিরোনাম ট্যাগ','Product Types'=>'পণ্যের প্রকারভেদ','Products'=>'পণ্যসমূহ','Quantity'=>'পরিমাণ','Quantity Selector on Archives'=>'আর্কাইভে পরিমাণ নির্বাচক','Quick Checkout Behavior'=>'দ্রুত চেকআউট আচরণ','Quick View'=>'দ্রুত দেখুন','Quick View Content'=>'দ্রুত দেখুন বিষয়বস্তু','Read More Button Text'=>'আরও পড়ুন','Recent Products'=>'সাম্প্রতিক পণ্য','Redirect After Add to Cart'=>'কার্টে যোগ করার পরে পুনঃনির্দেশ','Redirect to Cart Page'=>'কার্ট পেজে পুনঃনির্দেশ করুন','Redirect to Checkout'=>'চেকআউটে পুনঃনির্দেশ করুন','Reduced Abandonment: Customers can review their cart without losing their place on your site
'=>'পরিত্যক্ত হওয়ার হার হ্রাস: গ্রাহকরা আপনার সাইটে তাদের অবস্থান না হারিয়ে তাদের কার্ট পর্যালোচনা করতে পারবেন','Reinstall & Activate Pro Plugin'=>'প্রো প্লাগইন পুনরায় ইনস্টল ও সক্রিয় করুন','Remove Button'=>'মুছে ফেলুন বোতাম','Remove checkout fields
'=>'চেকআউট ফিল্ডগুলি সরান','Remove Product Button'=>'পণ্য সরান বোতাম','Remove this item'=>'এই আইটেমটি সরান','Renderer not available.'=>'রেন্ডারার উপলব্ধ নয়।','Replace Add to Cart Button'=>'কার্টে যোগ করুন বোতামটি প্রতিস্থাপন করুন','Responsive design works perfectly on all devices.

'=>'রেসপন্সিভ ডিজাইন সব ডিভাইসে পুরোপুরি কাজ করে।','Right'=>'ডান','Sales Boost: Easy access to cart encourages completion of purchases
'=>'বিক্রয় বৃদ্ধি: কার্টে সহজ প্রবেশাধিকার ক্রয় সম্পন্ন করতে উৎসাহিত করে','Save Changes'=>'পরিবর্তনগুলি সংরক্ষণ করুন','Search Results'=>'অনুসন্ধানের ফলাফল','Secondary Color'=>'মাধ্যমিক রঙ','Select All'=>'সবগুলো নির্বাচন করুন','Select fields to remove'=>'মুছে ফেলার জন্য ক্ষেত্রগুলি নির্বাচন করুন','Select options'=>'বিকল্প নির্বাচন করুন','Select the layout for the one-page checkout form.'=>'এক-পৃষ্ঠার চেকআউট ফর্মের জন্য বিন্যাস নির্বাচন করুন।','selected '=>'নির্বাচিত','Separate'=>'আলাদা করুন','Set a different button text for mobile devices. Leave empty to use the default text.

'=>'মোবাইল ডিভাইসের জন্য একটি ভিন্ন বোতাম টেক্সট সেট করুন। ডিফল্ট টেক্সট ব্যবহার করতে খালি রাখুন।','Set the default quantity when adding products to cart from archive pages.'=>'আর্কাইভ পেজ থেকে পণ্য কার্টে যোগ করার সময় ডিফল্ট পরিমাণ সেট করুন।','Set the left position of the floating cart.'=>'ফ্লোটিং কার্টের বাম অবস্থান সেট করুন।','Set the priority of the one-page checkout form. The default value is 9, but not all values work with every theme. So, adjust it based on your theme.'=>'এক-পৃষ্ঠার চেকআউট ফর্মের অগ্রাধিকার সেট করুন। ডিফল্ট মান হল ৯, তবে সব থিমের সাথে সব মান কাজ করে না। তাই, আপনার থিম অনুযায়ী এটি সামঞ্জস্য করুন।','Set the top position of the floating cart.'=>'ফ্লোটিং কার্টের উপরের অবস্থান সেট করুন।','Settings'=>'সেটিংস','Shield'=>'ঢাল','Ship to a different address?'=>'অন্য ঠিকানায় পাঠান?','Shipping'=>'শিপিং','Shopping Bag'=>'শপিং ব্যাগ','Shopping Bag Icon'=>'শপিং ব্যাগ আইকন','Short Description'=>'সংক্ষিপ্ত বিবরণ','Shortcode:
'=>'শর্টকোড:','Shortcodes'=>'শর্টকোড','Show Checkout Link'=>'চেকআউট লিঙ্ক দেখান','Show Confirmation Dialog'=>'নিশ্চিতকরণ ডায়ালগ দেখান','Show For Types (comma-separated)'=>'ধরন অনুযায়ী দেখান (কমা দ্বারা পৃথক করা)','Show license key'=>'লাইসেন্স কী দেখান','Show only the icon (without text) on mobile devices to save space.

'=>'মোবাইল ডিভাইসে জায়গা বাঁচাতে শুধুমাত্র আইকনটি (লেখা ছাড়া) দেখান।','Show Variation Selection in Archive pages'=>'আর্কাইভ পেজে ভ্যারিয়েশন নির্বাচন দেখান','Show Variation Title'=>'পরিবর্তনের শিরোনাম দেখান','Show View Cart Link'=>'কার্ট দেখুন লিঙ্ক দেখান','Side Cart Slide-in'=>'সাইড কার্ট স্লাইড-ইন','Simple Products'=>'সাধারণ পণ্য','Single Product Page'=>'একক পণ্য পাতা','Single Product Pages'=>'একক পণ্য পৃষ্ঠা','Size'=>'আকার','SKU'=>'SKU','Small'=>'ছোট','Social Sharing'=>'সামাজিক ভাগ করে নেওয়া','Star'=>'তারকা','State / District'=>'রাজ্য / জেলা','Sticky Add to Cart on Mobile'=>'মোবাইলে স্টিকি অ্যাড টু কার্ট','Street address'=>'রাস্তার ঠিকানা','Subtotal'=>'মোট','Subtotal '=>'মোট','Success Message'=>'সফলতার বার্তা','Supports all major payment processors.

'=>'সমস্ত প্রধান পেমেন্ট প্রসেসর সমর্থন করে।','Text'=>'টেক্সট','Text Color'=>'টেক্সট রঙ','Text Color
'=>'টেক্সট রঙ','Text Manage'=>'ব্যবস্থাপনা করুন','Text Only'=>'টেক্সট শুধুমাত্র','Text with Icon'=>'আইকন সহ টেক্সট','Text:'=>'Add to cart','Thank you for installing One Page Quick Checkout for WooCommerce! Streamline your WooCommerce checkout process and boost your conversion rates with our easy-to-configure solution.

'=>'WooCommerce-এর জন্য One Page Quick Checkout ইনস্টল করার জন্য ধন্যবাদ! আমাদের সহজে কনফিগার করা সমাধান দিয়ে আপনার WooCommerce চেকআউট প্রক্রিয়াটিকে সুগম করুন এবং আপনার রূপান্তর হার বৃদ্ধি করুন।','The checkout form appears on the front end when the cart is not empty.'=>'কার্ট খালি না থাকলে চেকআউট ফর্মটি ফ্রন্ট এন্ডে প্রদর্শিত হয়।','The event action name used for analytics tracking.'=>'অ্যানালিটিক্স ট্র্যাকিংয়ের জন্য ব্যবহৃত ইভেন্ট অ্যাকশনের নাম।','The event category name used for analytics tracking.'=>'বিশ্লেষণ ট্র্যাকিংয়ের জন্য ব্যবহৃত ইভেন্ট ক্যাটাগরির নাম।','Theme Compatibility Mode'=>'থিম সামঞ্জস্য মোড','This shortcode will display a buy now button for the current product when used on product pages.

'=>'এই শর্টকোডটি প্রোডাক্ট পেজগুলিতে ব্যবহার করা হলে বর্তমান প্রোডাক্টের জন্য একটি \'এখনই কিনুন\' বাটন প্রদর্শন করবে।','Thumbs Up'=>'থাম্বস আপ','Tips:
'=>'টিপস:','Top'=>'শীর্ষ','Top Position'=>'শীর্ষ অবস্থান','Total '=>'মোট','Town / City'=>'শহর','Track Quick View Events'=>'দ্রুত ভিউ ইভেন্টগুলি ট্র্যাক করুন','Track when customers use quick view in Google Analytics or other analytics tools.'=>'Google Analytics বা অন্যান্য অ্যানালিটিক্স টুলে গ্রাহকরা কখন কুইক ভিউ ব্যবহার করে তা ট্র্যাক করুন।','Transform your WooCommerce store with instant purchase buttons that bypass the traditional cart process. Our plugin automatically adds buy now buttons on single product and archive pages, but you have complete control over placement and customization.

'=>'আপনার WooCommerce স্টোরকে তাৎক্ষণিক ক্রয় বোতামের মাধ্যমে রূপান্তর করুন যা ঐতিহ্যবাহী কার্ট প্রক্রিয়াকে এড়িয়ে যায়। আমাদের প্লাগইনটি একক পণ্য এবং আর্কাইভ পেজগুলিতে স্বয়ংক্রিয়ভাবে \'এখনই কিনুন\' বোতাম যুক্ত করে, তবে প্লেসমেন্ট এবং কাস্টমাইজেশনের উপর আপনার সম্পূর্ণ নিয়ন্ত্রণ রয়েছে।','Translations'=>'অনুবাদসমূহ','Trust Badge Items'=>'ট্রাস্ট ব্যাজ আইটেম','Trust Badges Configuration'=>'ট্রাস্ট ব্যাজ কনফিগারেশন','Tutorials'=>'টিউটোরিয়াল','Upgrade to Pro
'=>'প্রো-তে আপগ্রেড করুন','Upsells'=>'আপসেল','Use !important CSS rules to override theme styling (use only if needed).'=>'থিম স্টাইলিং ওভাররাইড করতে !important CSS নিয়ম ব্যবহার করুন (শুধুমাত্র প্রয়োজনে ব্যবহার করুন)।','Use our widget or block (Buy Now Button) for easier implementation.

'=>'সহজ বাস্তবায়নের জন্য আমাদের উইজেট বা ব্লক (এখনই কিনুন বোতাম) ব্যবহার করুন।','Use our widget or block (One-page checkout) for easier implementation.

'=>'সহজ বাস্তবায়নের জন্য আমাদের উইজেট বা ব্লক (এক-পৃষ্ঠার চেকআউট) ব্যবহার করুন।','Variable Product Button Text'=>'পরিবর্তনশীল পণ্যের বোতামের লেখা','Variable Products'=>'পরিবর্তনশীল পণ্য','Variation ID'=>'পরিবর্তন আইডি','Variation ID (optional)'=>'পরিবর্তন আইডি (ঐচ্ছিক)','Variation Selection Layout'=>'পরিবর্তন নির্বাচন বিন্যাস','Vertical List'=>'উল্লম্ব তালিকা','View Demo'=>'ডেমো দেখুন','View Details Link'=>'বিস্তারিত দেখুন লিঙ্ক','View Documentation'=>'ডকুমেন্টেশন দেখুন','Website'=>'ওয়েবসাইট','Welcome to One Page Quick Checkout for WooCommerce
'=>'WooCommerce এর জন্য ওয়ান পেজ কুইক চেকআউটে স্বাগতম','When enabled, customers can use keyboard arrows to navigate between products in quick view and ESC to close.'=>'সক্ষম করা হলে, গ্রাহকরা কুইক ভিউতে পণ্যগুলির মধ্যে নেভিগেট করতে কীবোর্ড তীরগুলি এবং বন্ধ করতে ESC ব্যবহার করতে পারবেন।','When enabled, customers will see a confirmation dialog before proceeding to checkout.'=>'সক্ষম করা হলে, গ্রাহকরা চেকআউটে যাওয়ার আগে একটি নিশ্চিতকরণ ডায়ালগ দেখতে পাবেন।','When enabled, the cart will be emptied before adding the new product. This creates a single-product checkout experience.'=>'সক্ষম করা হলে, নতুন পণ্য যোগ করার আগে কার্ট খালি করা হবে। এটি একক-পণ্য চেকআউট অভিজ্ঞতা তৈরি করে।','When enabled, the direct checkout button will be available for guest users. When disabled, only logged-in users will see the button.'=>'সক্ষম করা হলে, অতিথি ব্যবহারকারীদের জন্য সরাসরি চেকআউট বোতামটি উপলব্ধ থাকবে। নিষ্ক্রিয় করা হলে, শুধুমাত্র লগইন করা ব্যবহারকারীরা বোতামটি দেখতে পাবেন।','When enabled, the quick view functionality will be optimized for mobile devices.'=>'সক্ষম করা হলে, কুইক ভিউ কার্যকারিতা মোবাইল ডিভাইসের জন্য অপ্টিমাইজ করা হবে।','When enabled, the quick view popup will automatically close after adding a product to cart.'=>'সক্ষম করা হলে, পণ্য কার্টে যোগ করার পরে কুইক ভিউ পপআপটি স্বয়ংক্রিয়ভাবে বন্ধ হয়ে যাবে।','When enabled, the select option button will be hidden on variable product pages.'=>'সক্ষম করা হলে, ভেরিয়েবল প্রোডাক্ট পেজগুলিতে সিলেক্ট অপশন বাটনটি লুকানো থাকবে।','When enabled, the variation selection will be shown on archive pages.'=>'সক্ষম করা হলে, ভ্যারিয়েশন নির্বাচন আর্কাইভ পেজগুলিতে দেখানো হবে।','When enabled, the variation title will be shown on archive pages.'=>'সক্ষম করা হলে, ভ্যারিয়েশনের শিরোনাম আর্কাইভ পেজগুলিতে দেখানো হবে।','Widgets'=>'উইজেট','Widgets & Shortcodes'=>'উইজেট এবং শর্টকোড','Width'=>'প্রস্থ','WooCommerce Add To Cart'=>'WooCommerce কার্টে যোগ করুন','WooCommerce Direct Checkout'=>'WooCommerce সরাসরি চেকআউট','Woocommerce privacy policy text'=>'WooCommerce গোপনীয়তা নীতি পাঠ্য','WooCommerce Quick View'=>'WooCommerce কুইক ভিউ','WooCommerce shows a continue shopping button after a product is added to cart, with this option you can disable that link so user remain on checkout page.

'=>'পণ্য কার্টে যোগ করার পরে WooCommerce একটি কেনাকাটা চালিয়ে যান বোতাম দেখায়, এই বিকল্পটির মাধ্যমে আপনি সেই লিঙ্কটি নিষ্ক্রিয় করতে পারেন যাতে ব্যবহারকারী চেকআউট পৃষ্ঠায় থাকেন।','Yes'=>'হ্যাঁ','You can find \'Additional information\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'অতিরিক্ত তথ্য\' খুঁজে পেতে পারেন।','You can find \'Billing details\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'বিলিং বিবরণ\' খুঁজে পেতে পারেন।','You can find \'City\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'শহর\' খুঁজে পেতে পারেন।','You can find \'Complete your purchase using the form below.\' in the checkout form or drawer.'=>'আপনি নিচের ফর্মটি ব্যবহার করে আপনার কেনাকাটা সম্পন্ন করতে পারেন।','You can find \'Country / Region\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'দেশ / অঞ্চল\' খুঁজে পেতে পারেন।','You can find \'Country\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'দেশ\' খুঁজে পেতে পারেন।','You can find \'Discount\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'ডিসকাউন্ট\' খুঁজে পেতে পারেন।','You can find \'District\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'জেলা\' খুঁজে পেতে পারেন।','You can find \'Email address\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'ইমেল ঠিকানা\' খুঁজে পেতে পারেন।','You can find \'First name\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'প্রথম নাম\' খুঁজে পেতে পারেন।','You can find \'First Name\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'প্রথম নাম\' খুঁজে পেতে পারেন।','You can find \'Have a coupon?\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'আপনার কি কোনো কুপন আছে?\' খুঁজে পেতে পারেন।','You can find \'If you have a coupon code, please apply it below.\' in the checkout form or drawer.'=>'আপনার যদি কোনো কুপন কোড থাকে, তাহলে অনুগ্রহ করে নিচে সেটি প্রয়োগ করুন।','You can find \'Last Name\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'শেষ নাম\' খুঁজে পেতে পারেন।','You can find \'Last name\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'শেষ নাম\' খুঁজে পেতে পারেন।','You can find \'Order notes\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'অর্ডার নোটস\' খুঁজে পেতে পারেন।','You can find \'Phone\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'ফোন\' খুঁজে পেতে পারেন।','You can find \'Place Order Button\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'অর্ডার দিন বোতাম\' খুঁজে পেতে পারেন।','You can find \'Place order\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'অর্ডার দিন\' খুঁজে পেতে পারেন।','You can find \'Postcode / ZIP\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'পোস্টকোড / জিপ\' খুঁজে পেতে পারেন।','You can find \'Product\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'পণ্য\' খুঁজে পেতে পারেন।','You can find \'Select All\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'সব নির্বাচন করুন\' খুঁজে পেতে পারেন।','You can find \'selected\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'নির্বাচিত\' খুঁজে পেতে পারেন।','You can find \'Ship to a different address?\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'অন্য ঠিকানায় পাঠান?\' খুঁজে পেতে পারেন।','You can find \'Shipping\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'শিপিং\' খুঁজে পেতে পারেন।','You can find \'State / District\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'রাজ্য / জেলা\' খুঁজে পেতে পারেন।','You can find \'Street address\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'রাস্তার ঠিকানা\' খুঁজে পেতে পারেন।','You can find \'Subtotal\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'মোট\' খুঁজে পেতে পারেন।','You can find \'Total\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'মোট\' খুঁজে পেতে পারেন।','You can find \'Town / City\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'শহর/নগর\' খুঁজে পেতে পারেন।','You can find \'Woocommerce privacy policy text\' in the checkout form or drawer.'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'WooCommerce গোপনীয়তা নীতি পাঠ্য\' খুঁজে পেতে পারেন।','You can find \'You may also like\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'আপনারও পছন্দ হতে পারে\' খুঁজে পেতে পারেন।','You can find \'Your Cart\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'আপনার কার্ট\' খুঁজে পেতে পারেন।','You can find \'Your order\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'আপনার অর্ডার\' খুঁজে পেতে পারেন।','You can find \'Zip Code\' in the checkout form or drawer.

'=>'আপনি চেকআউট ফর্ম বা ড্রয়ারে \'জিপ কোড\' খুঁজে পেতে পারেন।','You can use buy now button anywhere on your site with this shortcode.

'=>'আপনি এই শর্টকোড ব্যবহার করে আপনার সাইটের যেকোনো জায়গায় \'এখনই কিনুন\' বোতাম ব্যবহার করতে পারেন।','You can use one page checkout anywhere on your site with this shortcode.

'=>'আপনি এই শর্টকোড ব্যবহার করে আপনার সাইটের যেকোনো জায়গায় এক পৃষ্ঠার চেকআউট ব্যবহার করতে পারেন।','You have a valid license but the Pro plugin is not active.'=>'আপনার একটি বৈধ লাইসেন্স আছে কিন্তু প্রো প্লাগইনটি সক্রিয় নেই।','You may also like'=>'আপনারও ভালো লাগতে পারে','Your Cart'=>'আপনার কার্ট','Your license is active and the Pro plugin is running.'=>'আপনার লাইসেন্স সক্রিয় এবং প্রো প্লাগইন চলছে।','Your license is currently active.'=>'আপনার লাইসেন্স বর্তমানে সক্রিয় আছে।','Your order'=>'আপনার অর্ডার','Zip Code'=>'জিপ কোড']];
