<?php
if (! defined('ABSPATH')) exit; // Exit if accessed directly

$onepaquc_checkoutformfields = [
    "your_cart" => "Your Cart",
    "btn_remove" => "Remove Button",
    "txt_subtotal" => "Subtotal",
    "txt_checkout" => "Place order",
    "txt_billing_details" => "Billing details",
    "txt_email_address" => "Email address",
    "txt_first_name" => "First name",
    "txt_last_name" => "Last name",
    "txt_country" => "Country / Region",
    "txt_street" => "Street address",
    "txt_city" => "Town / City",
    "txt_district" => "District",
    "txt_postcode" => 'Postcode / ZIP',
    "txt_phone_number" => "Phone",
    "txt_notes" => "Order notes",
    "txt_product" => "Product",
    "txt_shipping" => "Shipping",
    "txt_additional_info" => "Additional information",
    "txt_your_order" => "Your order",
    "txt_shipping_address_head" => "Ship to a different address?",
    "txt_total" => "Total",
    "btn_place_order" => "Place Order Button",
    "txt-woocommerce-privacy-policy-text" => "Woocommerce privacy policy text",
    "txt-have_coupon" => "Have a coupon?",
    "txt-apply_coupon_below" => "If you have a coupon code, please apply it below.",
    "txt-complete_your_purchase" => "Complete your purchase using the form below.",
];

// archive & single product page text

$onepaquc_productpageformfields = [
    "txt-add-to-cart" => "Add to cart",
    "txt-select-options" => "Select options",
    "txt-read-more" => "Read more",
    "rmenu_grouped_add_to_cart_text" => "View products",
    "rmenu_out_of_stock_text" => "Out of stock"
];

$onepaquc_rcheckoutformfields = [
    'first_name' => ['title' => 'First Name', 'selector' => '#billing_first_name_field, #shipping_first_name_field'],
    'last_name'  => ['title' => 'Last Name', 'selector' => '#billing_last_name_field, #shipping_last_name_field'],
    'country'      => ['title' => 'Country', 'selector' => '#billing_country_field, #shipping_country_field'],
    'state'      => ['title' => 'State / District', 'selector' => '#billing_state_field, #shipping_state_field'],
    'city'       => ['title' => 'City', 'selector' => '#billing_city_field, #shipping_city_field'],
    'postcode'   => ['title' => 'Zip Code', 'selector' => '#billing_postcode_field, #shipping_postcode_field'],
    'address_1'  => ['title' => 'Address 1', 'selector' => '#billing_address_1_field, #shipping_address_1_field'],
    'address_2'  => ['title' => 'Address 2', 'selector' => '#billing_address_2_field, #shipping_address_2_field'],
    'phone'      => ['title' => 'Phone', 'selector' => '#billing_phone_field'],
    'email'      => ['title' => 'Email', 'selector' => '#billing_email_field'],
    'company'    => ['title' => 'Company', 'selector' => '#billing_company_field'],
    'notes'     => ['title' => 'Notes', 'selector' => '#order_comments_field'],
];

global $onepaquc_onepaquc_allowed_tags;


$onepaquc_onepaquc_allowed_tags = array(
    'a' => array(
        'href' => array(),
        'title' => array(),
        'class' => array(),
        'target' => array(), // Allow target attribute for links
        'style' => array(),
        'id' => array(),
    ),
    'strong' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'em' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'li' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
        'data-product-id' => array(),
        'data-cart-item-key' => array(),
    ),
    'div' => array(
        'class' => array(),
        'id' => array(), // Allow id for divs
        'style' => array(),
    ),
    'img' => array(
        'src' => array(),
        'alt' => array(),
        'class' => array(),
        'width' => array(), // Allow width attribute
        'height' => array(), // Allow height attribute
        'style' => array(),
        'id' => array(),
        'srcset' => array(),
        'sizes' => array(),
        'loading' => array(),
    ),
    'h1' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ), // Allow h1
    'h2' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'h3' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ), // Allow h3
    'h4' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ), // Allow h4
    'h5' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ), // Allow h5
    'h6' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ), // Allow h6
    'span' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'p' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'br' => array(
        'style' => array(),
        'class' => array(),
    ), // Allow line breaks
    'blockquote' => array(
        'cite' => array(), // Allow cite attribute for blockquotes
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'table' => array(
        'class' => array(),
        'style' => array(), // Allow inline styles
        'id' => array(),
    ),
    'tr' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'td' => array(
        'class' => array(),
        'colspan' => array(), // Allow colspan attribute
        'rowspan' => array(), // Allow rowspan attribute
        'style' => array(),
        'id' => array(),
    ),
    'th' => array(
        'class' => array(),
        'colspan' => array(),
        'rowspan' => array(),
        'style' => array(),
        'id' => array(),
    ),
    'ul' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ), // Allow unordered lists
    'ol' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
    ), // Allow ordered lists
    'script' => array(
        'type' => array(),
        'src' => array(),
        'async' => array(),
        'defer' => array(),
        'charset' => array(),
    ), // Be cautious with scripts

    // Style and Meta Tags
    'style' => array(
        'type' => array(),
        'media' => array(),
        'scoped' => array(),
    ),
    'link' => array(
        'rel' => array(),
        'href' => array(),
        'type' => array(),
        'media' => array(),
        'sizes' => array(),
        'hreflang' => array(),
        'crossorigin' => array(),
    ),
    'meta' => array(
        'name' => array(),
        'content' => array(),
        'http-equiv' => array(),
        'charset' => array(),
        'property' => array(), // For Open Graph
    ),
    'title' => array(),
    'base' => array(
        'href' => array(),
        'target' => array(),
    ),

    // Document Structure
    'html' => array(
        'lang' => array(),
        'dir' => array(),
        'class' => array(),
        'style' => array(),
    ),
    'head' => array(),
    'body' => array(
        'class' => array(),
        'id' => array(),
        'style' => array(),
        'onload' => array(),
    ),
    'header' => array(
        'class' => array(),
        'id' => array(),
        'style' => array(),
        'role' => array(),
    ),
    'footer' => array(
        'class' => array(),
        'id' => array(),
        'style' => array(),
        'role' => array(),
    ),
    'nav' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
        'role' => array(),
    ),
    'main' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
        'role' => array(),
    ),
    'section' => array(
        'class' => array(),
        'id' => array(),
        'style' => array(),
        'role' => array(),
    ),
    'article' => array(
        'class' => array(),
        'style' => array(),
        'id' => array(),
        'role' => array(),
    ),
    'aside' => array(
        'class' => array(),
        'id' => array(),
        'style' => array(),
        'role' => array(),
    ),

    // Form Elements
    'form' => array(
        'action' => array(),
        'method' => array(),
        'style' => array(),
        'enctype' => array(),
        'target' => array(),
        'name' => array(),
        'id' => array(),
        'class' => array(),
        'autocomplete' => array(),
        'novalidate' => array(),
        'data-mobile-style' => array(),
        'data-product_show_settings' => array(),
        'data-product_selector' => array(),
        'data-pagination_selector' => array(),
        'data-layout' => array(),
    ),
    'input' => array(
        'type' => array(),
        'name' => array(),
        'value' => array(),
        'style' => array(),
        'placeholder' => array(),
        'id' => array(),
        'class' => array(),
        'required' => array(),
        'disabled' => array(),
        'readonly' => array(),
        'checked' => array(),
        'selected' => array(),
        'multiple' => array(),
        'min' => array(),
        'max' => array(),
        'step' => array(),
        'pattern' => array(),
        'maxlength' => array(),
        'minlength' => array(),
        'size' => array(),
        'autocomplete' => array(),
        'autofocus' => array(),
        'form' => array(),
        'formaction' => array(),
        'formmethod' => array(),
        'formtarget' => array(),
        'formnovalidate' => array(),
        'accept' => array(),
        'alt' => array(),
        'src' => array(),
        'width' => array(),
        'height' => array(),
    ),
    'textarea' => array(
        'name' => array(),
        'id' => array(),
        'class' => array(),
        'placeholder' => array(),
        'rows' => array(),
        'style' => array(),
        'cols' => array(),
        'required' => array(),
        'disabled' => array(),
        'readonly' => array(),
        'maxlength' => array(),
        'minlength' => array(),
        'wrap' => array(),
        'autocomplete' => array(),
        'autofocus' => array(),
        'form' => array(),
    ),
    'select' => array(
        'name' => array(),
        'id' => array(),
        'class' => array(),
        'multiple' => array(),
        'size' => array(),
        'required' => array(),
        'style' => array(),
        'disabled' => array(),
        'autofocus' => array(),
        'form' => array(),
    ),
    'option' => array(
        'value' => array(),
        'selected' => array(),
        'style' => array(),
        'disabled' => array(),
        'label' => array(),
    ),
    'optgroup' => array(
        'label' => array(),
        'style' => array(),
        'disabled' => array(),
    ),
    'button' => array(
        'type' => array(),
        'name' => array(),
        'value' => array(),
        'id' => array(),
        'style' => array(),
        'class' => array(),
        'disabled' => array(),
        'form' => array(),
        'formaction' => array(),
        'formmethod' => array(),
        'formtarget' => array(),
        'formnovalidate' => array(),
        'autofocus' => array(),
    ),
    'label' => array(
        'for' => array(),
        'form' => array(),
        'id' => array(),
        'class' => array(),
        'style' => array(),
    ),
    'fieldset' => array(
        'disabled' => array(),
        'form' => array(),
        'style' => array(),
        'name' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'legend' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'datalist' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'output' => array(
        'for' => array(),
        'form' => array(),
        'name' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'plugrogress' => array(
        'value' => array(),
        'max' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'meter' => array(
        'value' => array(),
        'min' => array(),
        'max' => array(),
        'low' => array(),
        'style' => array(),
        'high' => array(),
        'optimum' => array(),
        'id' => array(),
        'class' => array(),
    ),

    // Media Elements
    'audio' => array(
        'src' => array(),
        'controls' => array(),
        'autoplay' => array(),
        'style' => array(),
        'loop' => array(),
        'muted' => array(),
        'preload' => array(),
        'crossorigin' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'video' => array(
        'src' => array(),
        'controls' => array(),
        'autoplay' => array(),
        'loop' => array(),
        'muted' => array(),
        'preload' => array(),
        'style' => array(),
        'poster' => array(),
        'width' => array(),
        'height' => array(),
        'crossorigin' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'source' => array(
        'src' => array(),
        'style' => array(),
        'type' => array(),
        'media' => array(),
        'sizes' => array(),
        'srcset' => array(),
    ),
    'track' => array(
        'kind' => array(),
        'src' => array(),
        'style' => array(),
        'srclang' => array(),
        'label' => array(),
        'default' => array(),
    ),
    'embed' => array(
        'src' => array(),
        'type' => array(),
        'width' => array(),
        'height' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'object' => array(
        'data' => array(),
        'type' => array(),
        'style' => array(),
        'name' => array(),
        'width' => array(),
        'height' => array(),
        'form' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'param' => array(
        'name' => array(),
        'value' => array(),
        'style' => array(),
    ),
    'iframe' => array(
        'src' => array(),
        'srcdoc' => array(),
        'name' => array(),
        'width' => array(),
        'style' => array(),
        'height' => array(),
        'sandbox' => array(),
        'allow' => array(),
        'allowfullscreen' => array(),
        'loading' => array(),
        'id' => array(),
        'class' => array(),
    ),

    // Interactive Elements
    'details' => array(
        'open' => array(),
        'id' => array(),
        'class' => array(),
        'style' => array(),
    ),
    'summary' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'dialog' => array(
        'open' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),

    // Text Content Elements
    'pre' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'code' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'kbd' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'samp' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'var' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'small' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'sub' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'sup' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'mark' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'del' => array(
        'datetime' => array(),
        'style' => array(),
        'cite' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'ins' => array(
        'datetime' => array(),
        'style' => array(),
        'cite' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'q' => array(
        'cite' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'cite' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'abbr' => array(
        'title' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'dfn' => array(
        'title' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'time' => array(
        'datetime' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'data' => array(
        'value' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'address' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),

    // Table Elements (Enhanced)
    'caption' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'thead' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'tbody' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'tfoot' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'colgroup' => array(
        'span' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),
    'col' => array(
        'span' => array(),
        'style' => array(),
        'id' => array(),
        'class' => array(),
    ),

    // Definition Lists
    'dl' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'dt' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'dd' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),

    // Ruby Annotations
    'ruby' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'rt' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'rp' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),

    // Bidirectional Text
    'bdi' => array(
        'dir' => array(),
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'bdo' => array(
        'dir' => array(),
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),

    // Web Components
    'template' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'slot' => array(
        'name' => array(),
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),

    // Math and Science
    'math' => array(
        'display' => array(),
        'xmlns' => array(),
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),

    // Canvas and Graphics
    'canvas' => array(
        'width' => array(),
        'height' => array(),
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),

    // Obsolete but sometimes needed
    'center' => array(
        'id' => array(),
        'style' => array(),
        'class' => array(),
    ),
    'font' => array(
        'size' => array(),
        'style' => array(),
        'color' => array(),
        'face' => array(),
        'id' => array(),
        'class' => array(),
    ),

    // SVG Tags
    'svg' => array(
        'xmlns' => array(),
        'viewbox' => array(), // lowercase
        'viewBox' => array(), // camelCase (standard)
        'width' => array(),
        'height' => array(),
        'class' => array(),
        'id' => array(),
        'style' => array(),
        'preserveAspectRatio' => array(),
        'version' => array(),
        'x' => array(),
        'y' => array(),
    ),
    'g' => array(
        'class' => array(),
        'id' => array(),
        'transform' => array(),
        'style' => array(),
        'fill' => array(),
        'stroke' => array(),
        'opacity' => array(),
    ),
    'path' => array(
        'd' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'stroke-width' => array(),
        'stroke-dasharray' => array(),
        'stroke-linecap' => array(),
        'stroke-linejoin' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'circle' => array(
        'cx' => array(),
        'cy' => array(),
        'r' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'stroke-width' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'ellipse' => array(
        'cx' => array(),
        'cy' => array(),
        'rx' => array(),
        'ry' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'stroke-width' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'rect' => array(
        'x' => array(),
        'y' => array(),
        'width' => array(),
        'height' => array(),
        'rx' => array(),
        'ry' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'stroke-width' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'line' => array(
        'x1' => array(),
        'y1' => array(),
        'x2' => array(),
        'y2' => array(),
        'class' => array(),
        'id' => array(),
        'stroke' => array(),
        'stroke-width' => array(),
        'stroke-dasharray' => array(),
        'stroke-linecap' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'polyline' => array(
        'points' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'stroke-width' => array(),
        'stroke-dasharray' => array(),
        'stroke-linecap' => array(),
        'stroke-linejoin' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'polygon' => array(
        'points' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'stroke-width' => array(),
        'stroke-dasharray' => array(),
        'stroke-linecap' => array(),
        'stroke-linejoin' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'text' => array(
        'x' => array(),
        'y' => array(),
        'dx' => array(),
        'dy' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'font-family' => array(),
        'font-size' => array(),
        'font-weight' => array(),
        'text-anchor' => array(),
        'dominant-baseline' => array(),
        'opacity' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'tspan' => array(
        'x' => array(),
        'y' => array(),
        'dx' => array(),
        'dy' => array(),
        'class' => array(),
        'id' => array(),
        'fill' => array(),
        'stroke' => array(),
        'font-family' => array(),
        'font-size' => array(),
        'font-weight' => array(),
        'text-anchor' => array(),
        'dominant-baseline' => array(),
        'opacity' => array(),
        'style' => array(),
    ),
    'use' => array(
        'href' => array(),
        'xlink:href' => array(),
        'x' => array(),
        'y' => array(),
        'width' => array(),
        'height' => array(),
        'class' => array(),
        'id' => array(),
        'transform' => array(),
        'style' => array(),
    ),
    'defs' => array(
        'class' => array(),
        'id' => array(),
        'style' => array(),
    ),
    'symbol' => array(
        'id' => array(),
        'viewBox' => array(),
        'class' => array(),
        'style' => array(),
        'preserveAspectRatio' => array(),
    ),
    'marker' => array(
        'id' => array(),
        'markerWidth' => array(),
        'markerHeight' => array(),
        'refX' => array(),
        'refY' => array(),
        'style' => array(),
        'orient' => array(),
        'markerUnits' => array(),
        'class' => array(),
    ),
    'linearGradient' => array(
        'id' => array(),
        'x1' => array(),
        'y1' => array(),
        'style' => array(),
        'x2' => array(),
        'y2' => array(),
        'gradientUnits' => array(),
        'gradientTransform' => array(),
        'class' => array(),
    ),
    'lineargradient' => array(
        'id' => array(),
        'x1' => array(),
        'y1' => array(),
        'style' => array(),
        'x2' => array(),
        'y2' => array(),
        'gradientUnits' => array(),
        'gradientTransform' => array(),
        'class' => array(),
    ),
    'radialGradient' => array(
        'id' => array(),
        'cx' => array(),
        'cy' => array(),
        'style' => array(),
        'r' => array(),
        'fx' => array(),
        'fy' => array(),
        'gradientUnits' => array(),
        'gradientTransform' => array(),
        'class' => array(),
    ),
    'radialgradient' => array(
        'id' => array(),
        'cx' => array(),
        'cy' => array(),
        'r' => array(),
        'style' => array(),
        'fx' => array(),
        'fy' => array(),
        'gradientUnits' => array(),
        'gradientTransform' => array(),
        'class' => array(),
    ),
    'stop' => array(
        'offset' => array(),
        'stop-color' => array(),
        'stop-opacity' => array(),
        'class' => array(),
        'style' => array(),
    ),
    'clipPath' => array(
        'id' => array(),
        'class' => array(),
        'style' => array(),
        'clipPathUnits' => array(),
    ),
    'mask' => array(
        'id' => array(),
        'class' => array(),
        'style' => array(),
        'maskUnits' => array(),
        'maskContentUnits' => array(),
        'x' => array(),
        'y' => array(),
        'width' => array(),
        'height' => array(),
    ),
    'pattern' => array(
        'id' => array(),
        'x' => array(),
        'y' => array(),
        'width' => array(),
        'style' => array(),
        'height' => array(),
        'patternUnits' => array(),
        'patternContentUnits' => array(),
        'patternTransform' => array(),
        'viewBox' => array(),
        'class' => array(),
    ),
    'filter' => array(
        'id' => array(),
        'x' => array(),
        'y' => array(),
        'style' => array(),
        'width' => array(),
        'height' => array(),
        'filterUnits' => array(),
        'primitiveUnits' => array(),
        'class' => array(),
    ),
    'feGaussianBlur' => array(
        'in' => array(),
        'style' => array(),
        'stdDeviation' => array(),
        'result' => array(),
    ),
    'feOffset' => array(
        'in' => array(),
        'dx' => array(),
        'style' => array(),
        'dy' => array(),
        'result' => array(),
    ),
    'feDropShadow' => array(
        'dx' => array(),
        'dy' => array(),
        'style' => array(),
        'stdDeviation' => array(),
        'flood-color' => array(),
        'flood-opacity' => array(),
    ),
    'image' => array(
        'x' => array(),
        'y' => array(),
        'width' => array(),
        'style' => array(),
        'height' => array(),
        'href' => array(),
        'xlink:href' => array(),
        'preserveAspectRatio' => array(),
        'class' => array(),
        'id' => array(),
        'opacity' => array(),
        'transform' => array(),
    ),
);


// Allow extensive CSS properties for WordPress
add_filter('safe_style_css', function ($styles) {
    return array_merge($styles, array(
        // Layout & Positioning
        'display',
        'visibility',
        'opacity',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'float',
        'clear',
        'clip',
        'clip-path',

        // Box Model
        'width',
        'height',
        'max-width',
        'max-height',
        'min-width',
        'min-height',
        'box-sizing',
        'aspect-ratio',

        // Margins & Padding
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'margin-block',
        'margin-inline',
        'margin-block-start',
        'margin-block-end',
        'margin-inline-start',
        'margin-inline-end',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'padding-block',
        'padding-inline',
        'padding-block-start',
        'padding-block-end',
        'padding-inline-start',
        'padding-inline-end',

        // Borders
        'border',
        'border-top',
        'border-right',
        'border-bottom',
        'border-left',
        'border-width',
        'border-top-width',
        'border-right-width',
        'border-bottom-width',
        'border-left-width',
        'border-style',
        'border-top-style',
        'border-right-style',
        'border-bottom-style',
        'border-left-style',
        'border-color',
        'border-top-color',
        'border-right-color',
        'border-bottom-color',
        'border-left-color',
        'border-radius',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-left-radius',
        'border-bottom-right-radius',
        'border-image',
        'border-image-source',
        'border-image-slice',
        'border-image-width',
        'border-image-outset',
        'border-image-repeat',
        'border-collapse',
        'border-spacing',

        // Background
        'background',
        'background-color',
        'background-image',
        'background-position',
        'background-position-x',
        'background-position-y',
        'background-repeat',
        'background-size',
        'background-attachment',
        'background-origin',
        'background-clip',
        'background-blend-mode',

        // Typography
        'color',
        'font',
        'font-family',
        'font-size',
        'font-weight',
        'font-style',
        'font-variant',
        'font-stretch',
        'font-display',
        'font-feature-settings',
        'font-variation-settings',
        'line-height',
        'letter-spacing',
        'word-spacing',
        'text-align',
        'text-align-last',
        'text-decoration',
        'text-decoration-line',
        'text-decoration-color',
        'text-decoration-style',
        'text-decoration-thickness',
        'text-transform',
        'text-indent',
        'text-shadow',
        'text-overflow',
        'text-rendering',
        'white-space',
        'word-wrap',
        'word-break',
        'overflow-wrap',
        'hyphens',
        'writing-mode',
        'text-orientation',
        'direction',
        'unicode-bidi',

        // List Styles
        'list-style',
        'list-style-type',
        'list-style-position',
        'list-style-image',

        // Table Styles
        'table-layout',
        'caption-side',
        'empty-cells',

        // Positioning & Alignment
        'vertical-align',
        'object-fit',
        'object-position',

        // Overflow & Scrolling
        'overflow',
        'overflow-x',
        'overflow-y',
        'overflow-anchor',
        'overscroll-behavior',
        'overscroll-behavior-x',
        'overscroll-behavior-y',
        'scroll-behavior',
        'scroll-margin',
        'scroll-padding',
        'scroll-snap-type',
        'scroll-snap-align',

        // Flexbox
        'flex',
        'flex-direction',
        'flex-wrap',
        'flex-flow',
        'justify-content',
        'align-items',
        'align-content',
        'align-self',
        'order',
        'flex-grow',
        'flex-shrink',
        'flex-basis',

        // Grid
        'grid',
        'grid-template',
        'grid-template-columns',
        'grid-template-rows',
        'grid-template-areas',
        'grid-auto-columns',
        'grid-auto-rows',
        'grid-auto-flow',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-area',
        'gap',
        'row-gap',
        'column-gap',
        'grid-gap',
        'grid-row-gap',
        'grid-column-gap',
        'justify-items',
        'justify-self',
        'place-items',
        'place-self',
        'place-content',

        // Transforms & Animations
        'transform',
        'transform-origin',
        'transform-style',
        'transform-box',
        'perspective',
        'perspective-origin',
        'backface-visibility',
        'transition',
        'transition-property',
        'transition-duration',
        'transition-timing-function',
        'transition-delay',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        'animation-fill-mode',
        'animation-play-state',

        // Visual Effects
        'box-shadow',
        'filter',
        'backdrop-filter',
        'mix-blend-mode',
        'isolation',
        'outline',
        'outline-color',
        'outline-style',
        'outline-width',
        'outline-offset',
        'resize',
        'cursor',
        'pointer-events',
        'user-select',
        'touch-action',

        // Print Styles
        'page-break-before',
        'page-break-after',
        'page-break-inside',
        'break-before',
        'break-after',
        'break-inside',

        // Logical Properties (modern CSS)
        'block-size',
        'inline-size',
        'min-block-size',
        'min-inline-size',
        'max-block-size',
        'max-inline-size',
        'inset',
        'inset-block',
        'inset-inline',
        'inset-block-start',
        'inset-block-end',
        'inset-inline-start',
        'inset-inline-end',

        // Container Queries
        'container-type',
        'container-name',
        'container',

        // Content & Generated Content
        'content',
        'quotes',
        'counter-reset',
        'counter-increment',

        // Miscellaneous
        'all',
        'contain',
        'will-change',
        'appearance',
        'caret-color',
        'tab-size',
        'column-count',
        'column-width',
        'column-gap',
        'column-rule',
        'column-rule-color',
        'column-rule-style',
        'column-rule-width',
        'column-span',
        'column-fill',
        'columns',

        // svg style
        'stop-color',
        'stop-opacity',
        'fill'

    ));
});
